[tool.poetry]
name = "app-backend"
version = "0.1.0"
description = ""
authors = ["olast45"]
readme = "README.md"
packages = [{include = "app_backend"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
